### ISSUE TITLE
Interior dimensions 

### ISSUE THREAD

**Issue by sbonaime** [SensorsIot/Project-Box-Templates#10]
Hi,

Maybe it could be more useful have as a parameter the interior width and length (and mayby height) instead of the exterior ones. I made those parameters which modify width and lenght. 

<img width="428" alt="Capture d’écran 2024-10-03 à 13 19 15" src="https://github.com/user-attachments/assets/c5e68b97-d311-4f28-9109-09b7b51055d0">

**Comment by SensorsIot** [comment]
Cool idea! And easy to add for everybody interested.

**Comment by sbonaime** [comment]
And can you also add the interior height ? Thanks !

**Comment by SensorsIot** [comment]
You can adapt all the formulas to your needs when you go to modify-->parameters-->model parameters
