### ISSUE TITLE
Can't delete all the holes

### ISSUE THREAD

**Issue by pfeerick** [SensorsIot/Project-Box-Templates#2]
Great design there Andreas, thanks for making this available.

I downloaded Fusion360 and opened this up, as I have a project in mind that could use this sort of enclosure. However, I wanted to delete both of the holes in the top part of the enclosure. One deletes fine, the other gives me either Extrude1 or Extrude4 errors. I also noticed I can't delete the hole on the side (although in this instance I actually want it). 

Any chance you can fix or change it so that is possible, or am I doing something wrong? As just selecting and deleting isn't 'just working' ;) Then again, I have never used Fusion360, so user error is entirely possible.

**Comment by SensorsIot** [comment]
The holes consist of a sketch and an extrusion. You find all elements of the box in the timeline on the left bottom. Hover over all rectangles (they show extrude) and klick each of them until you find the one which lights the hole you want to delete. Delete this extrusion and the hole is gone.

**Comment by pfeerick** [comment]
Wow... thanks! That worked (and made perfect sense!). 😄

**Comment by SensorsIot** [comment]
😄
