### ISSUE TITLE
can't push my file to repository

### ISSUE THREAD

**Issue by macdroid53** [SensorsIot/Project-Box-Templates#6]
I have added my FreeCAD version of the parametric box...but "git push origin" on my machine returns error: 403

**Comment by SensorsIot** [comment]
I think it worked now? At least I accepted a pull request from you.

**Comment by macdroid53** [comment]
Thanks.

It might have been my fault. I haven't used git  or github for a couple
years and I was trying to push directly to your github rather than forking
to my github and then making a pull request.

Anyway, saw all the FreeCAD comments and nobody doing anything, so I took
action.

Thanks again for all you do!
