### ISSUE TITLE
Template Box Fusion360.f3d

### ISSUE THREAD

**Issue by MicroMkr** [SensorsIot/Project-Box-Templates#8]
when you change the length of the lead the hatching grove from one side is diapering

**Comment by Collin7** [comment]
I am having this issue as well, if I change length or width of the box, I get a Mirror1 error, Chamfer1 edge missing.  Only happens for the top.  The box part is fine.  I have tried to fix, but I am not sure what the issue. is.

**Comment by kasmafan** [comment]
I have the same issue, when changing dimensions it gives an error "chanfer something lost bla bla bla".
I followed the original tutorial of adafruit, i was able to do the exact same box, but when I resize it, it gives the same error :D.

**Comment by MicroMkr** [comment]
pressing the mirror icon on the bottom solves this issue

**Comment by Collin7** [comment]
Hi @Arielhh  Im not sure I understand.  Which mirror icon do I need to click at the bottom?
I tried clicking mirror plane and mirror1 in the timeline, but still not working for me
![Error](https://user-images.githubusercontent.com/7162656/160464063-403d546f-9f18-466e-bb63-2813a163c17b.PNG)
.

**Comment by MicroMkr** [comment]
I am far for being an expert but i just found it by trial and error
you should go back to mirror and right click and edit to identical
![123](https://user-images.githubusercontent.com/4849568/160517916-e1516474-60c4-4b8f-b9c0-8bd41f8912b4.png)

**Comment by Collin7** [comment]
Hi @Arielhh Thank you so much. That worked, I can change box size now and it works.  I actually looked at that option, but just never tried to change it.  Thank you again.

**Comment by MicroMkr** [comment]
great :)

**Comment by schornhe** [comment]
great !!!
