### ISSUE TITLE
Top cover Lip problem

### ISSUE THREAD

**Issue by sbonaime** [SensorsIot/Project-Box-Templates#9]
Hi,
There a small mistake in your template for the top cover lip. One of the offset (d19) for the lip is shell + gap but the other one (d31)  is 1.7mm which is not a parameter ! It should be also shell + gap
![Capture d’écran 2024-10-03 à 13 07 26](https://github.com/user-attachments/assets/446727d3-328d-49bc-b767-ed788933fa73)
![Capture d’écran 2024-10-03 à 13 07 18](https://github.com/user-attachments/assets/b2aaaad4-6551-4efd-8ce7-9fd0f7e5eea4)

**Comment by SensorsIot** [comment]
Corrected. Thank you!
